const API_URL="https://script.google.com/macros/s/AKfycby8SCh-WsBXjBp1V-WsVKomUSWxlsWsnCUIMtNA8xTCNcnOqVGaQ-GCvyNY7XnzoLGgug/exec";
const SITE_BASE="https://thebigkorea.github.io/thebigkorea-hq/";
let ALL_NOTICES=[],IS_SAVING=false;
document.addEventListener("DOMContentLoaded",()=>{bindCategoryAndType();loadNotices();});
function bindCategoryAndType(){const c=document.getElementById("category"),t=document.getElementById("noticeType");if(!c||!t)return;const m={"공지사항":"main","긴급공지":"emergency","위생점검안내":"hygiene","인사공지":"hr","매출공지":"sales","인사복무":"discipline"};c.addEventListener("change",()=>t.value=m[c.value]||"main");}
async function loadNotices(){const b=document.getElementById("noticeList");if(b)b.innerHTML="공지사항을 불러오는 중입니다...";try{const r=await fetch(API_URL+"?action=getNotices&_="+Date.now(),{cache:"no-store"}),d=await r.json();if(!d.success)throw new Error(d.message||"조회 실패");ALL_NOTICES=d.notices||[];renderNotices(ALL_NOTICES);}catch(e){console.error(e);if(b)b.innerHTML="서버 연결 오류가 발생했습니다.";}}
function renderNotices(list){const b=document.getElementById("noticeList");if(!b)return;if(!list.length){b.innerHTML="등록된 공지사항이 없습니다.";return;}b.innerHTML=list.map(n=>{const imp=n.important==="Y",img=n.imageUrl||getNoticeImage(n.noticeType),file=n.fileUrl?`<button type="button" onclick="window.open('${escapeJs(n.fileUrl)}','_blank')">📎 첨부파일</button>`:"";return `<div class="notice-item"><div class="notice-thumb"><img src="${escapeHtml(img)}" alt="${escapeHtml(n.category)}"></div><div class="notice-main"><div class="notice-top"><span class="badge ${imp?"red":""}">${imp?"중요 · ":""}${escapeHtml(n.category)}</span><span>${formatDate(n.createdAt)}</span></div><div class="notice-title">${escapeHtml(n.title)}</div><div class="notice-content">${escapeHtml(n.content)}</div><div class="notice-info">대상 ${escapeHtml(n.target)} &nbsp; 작성자 ${escapeHtml(n.writer)} ${n.expireDate?`&nbsp; 종료 ${escapeHtml(n.expireDate)}`:""}</div><div class="notice-buttons"><button type="button" onclick="window.open('${SITE_BASE}notice-view.html?id=${encodeURIComponent(n.noticeId)}','_blank')">공지 확인하기</button>${file}<button type="button" onclick="copyNoticeLink('${escapeJs(n.noticeId)}')">링크 복사</button><button type="button" class="delete-btn" onclick="deleteNotice('${escapeJs(n.noticeId)}')">삭제</button></div></div></div>`}).join("");}
async function saveNotice(){if(IS_SAVING)return;const category=v("category"),target=v("target"),title=v("title").trim(),content=v("content").trim(),expireDate=v("expireDate"),important=v("important"),writer=v("writer").trim()||"관리자",noticeType=v("noticeType"),fileUrl=v("fileUrl").trim();if(!title)return alert("제목을 입력하세요.");if(!content)return alert("공지 내용을 입력하세요.");const btn=document.querySelector('button[onclick="saveNotice()"]');IS_SAVING=true;if(btn){btn.disabled=true;btn.dataset.old=btn.innerHTML;btn.innerHTML="등록 중...<br><small>잠시만 기다려주세요</small>";}try{const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),20000);let d;try{const r=await fetch(API_URL,{method:"POST",body:JSON.stringify({action:"saveNotice",category,target,title,content,expireDate,important,writer,noticeType,fileUrl}),signal:ctl.signal});clearTimeout(tm);d=await r.json();}catch(e){clearTimeout(tm);if(await confirmSavedNotice(title,content)){await finishSaveSuccess();return;}throw e;}if(d&&d.success){await finishSaveSuccess();return;}alert(d?.message||"공지 등록에 실패했습니다.");}catch(e){console.error(e);alert("서버 응답을 확인하지 못했습니다.\n공지 목록을 새로고침하여 등록 여부를 확인해주세요.");await loadNotices();}finally{IS_SAVING=false;if(btn){btn.disabled=false;btn.innerHTML=btn.dataset.old||"공지 등록";}}}
async function confirmSavedNotice(title,content){await new Promise(r=>setTimeout(r,1200));try{const r=await fetch(API_URL+"?action=getNotices&_="+Date.now(),{cache:"no-store"}),d=await r.json();if(!d.success)return false;ALL_NOTICES=d.notices||[];renderNotices(ALL_NOTICES);return ALL_NOTICES.some(n=>String(n.title||"").trim()===title&&String(n.content||"").trim()===content);}catch(e){return false;}}
async function finishSaveSuccess(){alert("공지사항이 등록되었습니다.");s("title","");s("content","");s("important","N");s("fileUrl","");s("expireDate","");await loadNotices();}
async function deleteNotice(id){if(!confirm("이 공지사항을 삭제할까요?"))return;try{const r=await fetch(API_URL,{method:"POST",body:JSON.stringify({action:"deleteNotice",noticeId:id})}),d=await r.json();if(d.success){alert("삭제되었습니다.");await loadNotices();}else alert(d.message||"삭제 실패");}catch(e){alert("서버 연결 오류가 발생했습니다.");}}
function copyNoticeLink(id){const n=ALL_NOTICES.find(x=>String(x.noticeId)===String(id));if(!n)return alert("공지 정보를 찾을 수 없습니다.");const type=normalizeNoticeType(n.noticeType,n.category),f={main:"notice-share-main.html",emergency:"notice-share-emergency.html",hygiene:"notice-share-hygiene.html",hr:"notice-share-hr.html",sales:"notice-share-sales.html",discipline:"notice-share-discipline.html"}[type]||"notice-share-main.html",url=SITE_BASE+f+"?id="+encodeURIComponent(id),text=`${n.title}\n\n${url}`;navigator.clipboard.writeText(text).then(()=>alert("공지 링크가 복사되었습니다.")).catch(()=>prompt("아래 내용을 복사하세요.",text));}
function normalizeNoticeType(type,cat){const ok=["main","emergency","hygiene","hr","sales","discipline"];type=String(type||"").trim();if(ok.includes(type))return type;return {"공지사항":"main","일반공지":"main","긴급공지":"emergency","위생점검안내":"hygiene","인사공지":"hr","매출공지":"sales","인사복무":"discipline"}[String(cat||"").trim()]||"main";}
function getNoticeImage(type){return SITE_BASE+"images/"+({main:"notice-main.png",emergency:"notice-emergency.png",hygiene:"notice-hygiene.png",hr:"notice-hr.png",sales:"notice-sales.png",discipline:"notice-discipline.png"}[type]||"notice-main.png");}
function formatDate(x){if(!x)return"";const d=new Date(x);return isNaN(d)?x:d.toLocaleDateString("ko-KR",{year:"numeric",month:"2-digit",day:"2-digit"});}
function v(id){return document.getElementById(id)?.value||"";} function s(id,x){const e=document.getElementById(id);if(e)e.value=x;}
function escapeHtml(x){return String(x||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function escapeJs(x){return String(x||"").replace(/\\/g,"\\\\").replace(/'/g,"\\'");}
