const API_URL="https://script.google.com/macros/s/AKfycbzD9fUFvLxl6-cZGm6IUslFQrZDJk3P6Ip8to2NEWiktC2HR9a9VPFK-fNlxdcc_yg/exec";
let ALL_TRIPS=[], COMPANIONS=[];
document.addEventListener("DOMContentLoaded",()=>{setToday();loadVehicles();loadHeadOfficeEmployees();loadTrips();document.getElementById("tripStartDate").addEventListener("change",syncEndDate);});
function localToday(){const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`;}
function setToday(){const t=localToday();document.getElementById("tripStartDate").value=t;document.getElementById("tripEndDate").value=t;document.getElementById("tripEndDate").min=t;}
function syncEndDate(){const s=value_("tripStartDate"),e=document.getElementById("tripEndDate");e.min=s;if(!e.value||e.value<s)e.value=s;}
async function loadHeadOfficeEmployees(){try{const d=await(await fetch(API_URL+"?action=getHeadOfficeEmployees")).json();if(!d.success)return;["userName","companionEmployee"].forEach(id=>{const el=document.getElementById(id);el.innerHTML=`<option value="">본사 직원 선택</option>`;(d.employees||[]).forEach(x=>{const o=document.createElement("option");o.value=x.name;o.textContent=x.name;el.appendChild(o);});});}catch(e){console.log(e);}}
async function loadVehicles(){try{const d=await(await fetch(API_URL+"?action=getVehicles")).json();if(!d.success)return;const s=document.getElementById("carNumber");s.innerHTML='<option value="">차량 선택</option>';d.vehicles.forEach(v=>{const o=document.createElement("option");o.value=v.carNumber;o.textContent=`${v.carNumber} / ${v.carModel}`;s.appendChild(o);});}catch(e){console.log(e);}}
function addCompanion(name){name=String(name||"").trim();if(!name||name===value_("userName")||COMPANIONS.includes(name))return;COMPANIONS.push(name);renderCompanionTags();}
function addSelectedCompanion(){addCompanion(value_("companionEmployee"));document.getElementById("companionEmployee").value="";}
function addDirectCompanions(){value_("companionDirect").split(/[,，\n]/).forEach(addCompanion);document.getElementById("companionDirect").value="";}
function removeCompanion(name){COMPANIONS=COMPANIONS.filter(x=>x!==name);renderCompanionTags();}
function renderCompanionTags(){document.getElementById("companionTags").innerHTML=COMPANIONS.map(n=>`<span class="companion-tag">${escapeHtml(n)} <button type="button" onclick='removeCompanion(${JSON.stringify(n)})'>×</button></span>`).join("");}
async function saveTrip(){const start=value_("tripStartDate"),end=value_("tripEndDate");if(!start||!end)return alert("출장 시작일과 종료일을 입력해주세요.");if(end<start)return alert("출장 종료일은 시작일보다 빠를 수 없습니다.");if(!value_("userName"))return alert("출장자를 선택해주세요.");const body={action:"saveTrip",tripStartDate:start,tripEndDate:end,userName:value_("userName"),companions:COMPANIONS,department:value_("department"),transportType:value_("transportType"),carNumber:value_("carNumber"),destination:value_("destination"),purpose:value_("purpose"),memo:value_("memo"),status:"승인대기"};try{const d=await(await fetch(API_URL,{method:"POST",body:JSON.stringify(body)})).json();if(d.success){alert("출장 신청이 저장되었습니다.");clearForm();loadTrips();}else alert(d.message||"오류가 발생했습니다.");}catch(e){console.log(e);alert("서버 연결 실패");}}
async function loadTrips(){try{const d=await(await fetch(API_URL+"?action=getTrips")).json();if(!d.success)return;ALL_TRIPS=d.trips||[];renderTrips();updateSummary();}catch(e){console.log(e);}}
function renderTrips(){const c=document.getElementById("tripList");c.innerHTML="";if(!ALL_TRIPS.length){c.innerHTML='<div class="empty">출장 신청내역이 없습니다.</div>';return;}ALL_TRIPS.forEach(t=>{const div=document.createElement("div");div.className="trip-item";const period=t.tripStartDate===t.tripEndDate?t.tripStartDate:`${t.tripStartDate} ~ ${t.tripEndDate}`;const companions=t.companions?`<div>동행자 : ${escapeHtml(t.companions)}</div>`:"";div.innerHTML=`<div class="trip-top"><div class="trip-name">${escapeHtml(t.userName)}</div><div class="trip-date">${period}</div></div><div class="trip-body"><div>부서 : ${escapeHtml(t.department)}</div>${companions}<div>차량 : ${escapeHtml(t.carNumber||"-")}</div><div>방문처 : ${escapeHtml(t.destination)}</div><div>출장목적 : ${escapeHtml(t.purpose)}</div><div>상태 : ${escapeHtml(t.status)}</div></div>`;c.appendChild(div);});}
function updateSummary(){document.getElementById("tripCount").textContent=number_(ALL_TRIPS.length);const today=localToday();document.getElementById("todayTripCount").textContent=number_(ALL_TRIPS.filter(t=>(t.tripStartDate||t.tripDate)<=today&&(t.tripEndDate||t.tripDate)>=today).length);}
function clearForm(){["department","destination","purpose","memo","companionDirect"].forEach(id=>document.getElementById(id).value="");document.getElementById("userName").value="";document.getElementById("carNumber").value="";COMPANIONS=[];renderCompanionTags();setToday();}
function value_(id){return document.getElementById(id)?.value||"";}function number_(n){return Number(n||0).toLocaleString();}function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));}
